[project]
name = "scrapingbackend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.140.0",
    "pdfminer-six>=20260107",
    "pillow>=12.3.0",
    "psycopg2>=2.9.12",
    "pydantic>=2.13.4",
    "pymupdf>=1.28.2",
    "pypdf>=6.16.2",
    "pytesseract>=0.3.13",
    "python-docx>=1.2.0",
    "python-multipart>=0.0.32",
    "qpdf>=0.2.0",
    "sqlalchemy[asyncio]>=2.0.51",
    "supabase>=2.31.0",
]
